### ISSUE TITLE
Create Event

### ISSUE THREAD

**Issue by jsabol** [CRGTMobile/electric-eel#26]
A user must be able to create a new event. (IBDWS-01,2- create/edit content).

**Comment by jsabol** [comment]
I'm confused by this statement under Create Event -- "This has two components: web based page and PDF page." -- where does the PDF page fit in?

**Comment by lnewlen86** [comment]
So this was a misplaced comment- sorry. Think that comment was regarding form creation. @calchus and I were discussing GPO requirements mention fillable forms..this sounds like PDF.  More detailed Registration may be done using a PDF form that a person fills out.
