### ISSUE TITLE
Edit Template

### ISSUE THREAD

**Issue by jsabol** [CRGTMobile/electric-eel#28]
A user must be able to easily edit the content of an existing event page template without having any technical (HTML) knowledge. Incorporates WYSIWYG

**Comment by jsabol** [comment]
Is this the ability to edit an event or edit a template? It says "event page template" ?

**Comment by lnewlen86** [comment]
No this is editing the template only (I read it as the event page layout) not the event content.

**Comment by lnewlen86** [comment]
there are two stories for "edit template"- 1)  edit a template layout easily (WYSIWYG), 2) ensuring that when you update the template you don't change the theme.  Editing an event should be its own separate story
