### ISSUE TITLE
Recent Activity

### ISSUE THREAD

**Issue by jsabol** [CRGTMobile/electric-eel#34]
Authorized users must be able to retrieve up to five previous versions and to continue work from a selected point.  (IBDWS -24)

**Comment by jsabol** [comment]
Who is an authorized user?

**Comment by lnewlen86** [comment]
I think we may need a separate story to outline a minimum of 3 roles: site administrator (had access to all) event approver (has access to approve, create, etc) , event creator (has ability to create, edit events, templates and submit for approval), and event attendee (external site user).

**Comment by jsabol** [comment]
So all user roles except for event attendee would have this access?
